# Cryptographic hashes for cr-sqlite v0.16.3 binaries
# Auto-generated by update-version.sh - do not edit manually
{
  "aarch64-darwin" = "sha256-3SX8QwdI+WBUSgjdZq9xnPhQWtJrBXFamzrcMiWhOWM=";
  "x86_64-darwin" = "sha256-1IJASVCrFh+NiYsJbVWAFxIOImhL8WeKAiDsPne/hiQ=";
  "x86_64-linux" = "sha256-F9uTWLanDAjL4btdEHtmNnc1SdHAzbAOYBTPCa4BqJI=";
  "aarch64-linux" = "sha256-wmqsZo258MRVo3y/uirhKaETE6H1swtL3O5pz6HR+Uo=";
}