# Cryptographic hashes for cr-sqlite v0.16.3 binaries
# Auto-generated by update-version.sh - do not edit manually
{
  "aarch64-darwin" = "sha256-3SX8QwdI+WBUSgjdZq9xnPhQWtJrBXFamzrcMiWhOWM=";
  "x86_64-darwin" = "sha256-mIXxfz6HN8Fim57GjYvnBx6enhS3O4r7hYu2zZSz5Rg=";
  "x86_64-linux" = "sha256-oA0WgzP1BOXXCo0Z7fBoPWa4sV0bidTKqxmCWEdQQWA=";
  "aarch64-linux" = "sha256-uWmW6u+5QroYc1/D/VuyQxgJv1SXXoqqlwblsLPJV7M=";
}