name: Cache Builds
on:
  push:
    branches: [main]

jobs:
  cache:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'subtleGradient'  # Only run on main repo
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    
    - uses: cachix/cachix-action@v16
      with:
        name: subtlegradient-sqlite-cr
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        skipPush: ${{ github.event_name == 'pull_request' }}
    
    # Build all platforms and push to cache
    - name: Build and cache all platforms
      run: |
        for system in x86_64-linux aarch64-linux x86_64-darwin aarch64-darwin; do
          echo "Building $system..."
          nix build .#packages.$system.default --no-link
        done