name: Cache Builds
on:
  push:
    branches: [main]

jobs:
  cache:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            system: x86_64-linux
          # Skip aarch64-linux without emulation/remote builders
          - os: macos-14
            system: aarch64-darwin
          - os: macos-13
            system: x86_64-darwin
    runs-on: ${{ matrix.os }}
    name: Cache ${{ matrix.system }}
    if: ${{ github.repository_owner == 'subtleGradient' }}  # Only run on main repo
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: DeterminateSystems/nix-installer-action@v9
    
    - uses: cachix/cachix-action@v16
      with:
        name: subtlegradient-sqlite-cr
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        skipPush: ${{ github.event_name == 'pull_request' }}
    
    - name: Build and cache
      run: nix build .#packages.${{ matrix.system }}.default --no-link